[tool.poetry]
name = "mkdocs-statblock-plugin"
version = "0.1"
description = "MkDocs plugin to format YAML within statblock superfences as HTML"
authors = ["Johannes Zwirchmayr <johannes.zwirchmayr@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
mkdocs = ">=1.6.0"
pyyaml = "*"

[tool.poetry.plugins."mkdocs.plugins"]
"statblock" = {git = "https://github.com/johannes-z/mkdocs-statblock-plugin.git", branch = "main"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
